name: bgmatting
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch=1.1.0=py3.6_cuda100_cudnn7_1
  - torchvision=0.3.0=py36_cu100_1
  - cudatoolkit=10.0.130=0
  - pillow=6.1.0
  - scikit-image==0.14.2
  - scipy==1.2.1
  - python=3.6
  - pip
  - pip:
      - tensorflow-gpu==1.14.0
      - numpy==1.17.0
      - opencv-python==3.4.5.20
      - pandas==1.0.3
      - tqdm==4.45.0
      - tensorboardx==2.0
